version: '3.8'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
services:
  postgresql_main:
    image: postgres:alpine
    container_name: postgresql_main
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./docker/postgresql/main/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volume/data/postgresql_main:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_MAIN_PORT}:5432"
    depends_on:
      - postgresql_shard1
      - postgresql_shard2
    networks:
      - backend
  postgresql_shard1:
    image: postgres:alpine
    container_name: postgresql_shard1
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./docker/postgresql/shard1/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volume/data/postgresql_shard1:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_SHARD1_PORT}:5432"
    networks:
      - backend
  postgresql_shard2:
    image: postgres:alpine
    container_name: postgresql_shard2
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./docker/postgresql/shard2/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volume/data/postgresql_shard2:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_SHARD2_PORT}:5432"
    networks:
      - backend
  postgresql_noshard:
    image: postgres:alpine
    container_name: postgresql_noshard
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./docker/postgresql/noshard/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volume/data/postgresql_noshard:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_NOSHARD_PORT}:5432"
    networks:
      - backend